# Build and run the monitoring server with: docker-compose up --build
# Dashboard available at: http://localhost:5000/dashboard (or ${MONITOR_PORT})
version: "3.9"

services:
  server:
    build:
      context: ./server
    restart: unless-stopped
    environment:
      DATABASE_PATH: /app/data/metrics.db
    volumes:
      - server_data:/app/data
    ports:
      - "${MONITOR_PORT:-5050}:5000"

volumes:
  server_data:
