# Build and run the stack with: docker-compose up --build
# Dashboard available at: http://localhost:5000/dashboard
version: "3.9"

services:
  server:
    build:
      context: ./server
    restart: unless-stopped
    environment:
      DATABASE_PATH: /app/data/metrics.db
    volumes:
      - server_data:/app/data
    ports:
      - "${MONITOR_PORT:-5000}:5000"

  client:
    build:
      context: ./client
    restart: unless-stopped
    environment:
      SERVER_URL: http://server:5000/metrics
      SCRAPE_INTERVAL: 30
    depends_on:
      - server

volumes:
  server_data:
